version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: memecoin-postgres-1
    restart: unless-stopped
    environment:
      POSTGRES_USER: memecoin
      POSTGRES_PASSWORD: memecoin123
      POSTGRES_DB: memecoin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
