version: '3.8'

services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/memecoin
      SPRING_DATASOURCE_USERNAME: memecoin
      SPRING_DATASOURCE_PASSWORD: memecoin123

  db:
    image: postgres:16
    container_name: memecoin-postgres-1
    restart: unless-stopped
    environment:
      POSTGRES_USER: memecoin
      POSTGRES_PASSWORD: memecoin123
      POSTGRES_DB: memecoin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:


